### ISSUE TITLE
Interior structure analysis revisions

### ISSUE THREAD

**Issue by ericagol** [ericagol/TRAPPIST1_Spitzer#11]
Martin Turbet & @CarolineDorn  - could you help me address these?

- [x] It is unclear to me what model the authors use for getting the interior structure, whether it is Dorn+ 2018, or by Zeng+ 2016. It seems that they have used the models by Zeng to infer the composition of the planets (core mass fraction and derived refractory ratios from this), and used Dorn for the mass radius relationships for Fig. 12. I recommend that the authors explain with more clarity which model they use for constraining composition, a brief description of the model (what chemistry is considered), and for consistency use the same one to obtain the mass-radius relationships displayed in Fig. 12 and 19. If you decide to show more than one model (Dorn+ and Zeng+) please explain the differences.

- [x] The authors mention core-free planets as a possibility for the structure of the Trappist-1 planets. Please mention what is the magnesium number of these planets.

- [x] ...the authors mention that core-free planets are ones that contain volatiles in the interior. This is most likely a misnomer. The fact that you would need more O to bind to Fe to have core-less planets, does not mean that there are volatiles inside the planet, as oxides are not volatiles. I recommend changing the wording.

- [x]  Rocky super-Earths appear to have a wider compositional distribution than that of stars. I recommend that the authors soften their take on refractory ratios being the same as that of the stars, and consider that the planets within the same system may have different values. This will entail changing some of the sections in the paper, including 10.3 and also 11.1.

- [x] The authors mention carbide planets as a possibility for their composition. Although many authors have invoked this exotic composition, stellar experts have shown that stars are not C/O rich and thus carbide planets are only theoretical at this point (Nisset et al 2014, Nissen 2015, Brewer and Fischer, 2016, Teske et al, 2014, Suarez-Andres et al, 2018). I recommend authors to either remove this as a possibility, or have an in-depth discussion as to the viability of carbide planets, so that there is more clarity in the community (especially for geoscientists that aren't aware of these details).

- [x] Please write all the core mass fraction estimates for all planets (not only h and c), as well as water inventory.

- [x] In page 23: Make explicit that the Fe/Mg ratios quoted for Trappist-1 and the Earth are by mol and not by weight.

- [x] Fig 12. is busy with the different colours for the mass-radius relationships and the equilibrium temperatures. I recommend the authors pick a different colour scheme for the T (or M-R relations) to help the reader.

- [x] Unfortunately, Fig. 18 is not very understandable. I suggest explaining more in the captions and labeling for each planet the different values of water mass fraction.

- [x] The models with a surface water layer have a different iron/magnesium ratio than the other cases.  Should we make these the same?

- [x] Also, we should make sure we are referencing the correct refractory composition abundance ratio papers - U18,  Lodders (2009), or Asplund.

- [x] remove Zeng+ from Figure 19.
- [x] update Fig 12
- [x] update Fig 15
- [x] update Fig 16
- [x] update Fig 18
- [x] update Fig 19
- [x] update Fig Table 9 with CMF values from Caroline's interior models.
- [x] add water mass fractions to Table 9.

**Comment by ericagol** [comment]
- [ ] Another question for @CarolineDorn :  why are the Fe/Mg = 0.83 and 0.95 lines so close to one another in the mass-radius relation plot?  Should the Fe/Mg = 0.83 really be 0.9 (from Asplund 2009)?

**Comment by CarolineDorn** [comment]
Ok, I sent you an email with all responses. 
Regarding Haiyang Wang's devolatization trend: they use the Sun-Earth devolatization trend and apply it to different stars. Since we do not have measured stellar abundances for Trappist-1, we could only use the Sun-Earth devolatilization trend. But changes are negligible on an M_R-plot (e.g., Earth does fall on the M-R curve that is calculated from solar abundances).

**Comment by ericagol** [comment]
@CarolineDorn Thanks, let's skip the devolatization trend!

**Comment by ericagol** [comment]
Update figures and table with new mass-radius relations:

- [ ] remove Zeng+ from Figure 19.
- [ ] update Fig 12
- [ ] update Fig 15
- [ ] update Fig 16
- [ ] update Fig 18
- [ ] update Fig 19
- [ ] update Fig Table 9.
