### ISSUE TITLE
Timing system & consistency

### ISSUE THREAD

**Issue by ericagol** [ericagol/TRAPPIST1_Spitzer#17]
@educrot 
- [x] Which timing system do the BJD times use (in Table 2 & 14)?  TDB?  UTC?
- [x] ... different observatories (also space observatories) can use different time standards, BJD_TDB or BJD_UTC.  Were the transit times corrected and unified prior the analysis? Is it possible that the presented outliers are related to this fact?

Table 15
- [x] The times presented here are in JD, but why not in BJD?

**Comment by ericagol** [comment]
@educrot  Should we cite http://dx.doi.org/10.1086/655938 ?

**Comment by educrot** [comment]
I will submit a pull request with the changes but just to answer your questions:

- BJD_TDB timings are used in Table 14 and 2

- Indeed the transit times were corrected and unified prior to the analysis. Therefore we do not believe this could be the origin for the presence of outliers

However, for Table 15 I don't know as I did not help filling up this table.

**Comment by ericagol** [comment]
@educrot Since Table 15 is derived from the transit-timing analysis, then these times use the same system as the observed times (i.e. `BJD_TDB`).

**Comment by ericagol** [comment]
@educrot  Thanks for your help.  I've now changed all instances of JD to BJD_TDB in the text and figure axis labels.
