### ISSUE TITLE
Consistency of transit depths

### ISSUE THREAD

**Issue by ericagol** [ericagol/TRAPPIST1_Spitzer#19]
@educrot  We can probably refer to Ducrot et al. (2020) regarding these issues:

- [x]  ...the authors used two Spitzer channels to calculate the Rp/Rs parameters, but they treated the planet-to-star radius ratios as identical in both passbands, which is not an adequate solution. There can be significant differences between the derived parameter values in the used channels. The authors should show that the differences in the Rp/Rs parameters are not significant, by presenting separate parameter values. In this case the weighted averages calculated with weights of 1/sigma^2 should be used to obtain the final Rp/Rs. In the case of significant differences between the channels, the smaller Rp/Rs value, in which the atmosphere is less significant, should be taken into account.

- [x]  Since the host is an active dwarf star, the authors should also check the transit-to-transit variability of the Rp/Rs parameters and eliminate discrepant transits.

- [x] Concerning the second comment of the authors, out of curiosity I was wondering if you had a table reporting all the timings outliers at hand in order to check any potential correlation? 

- [x]  I should check the photo dynamical model for these two transits to see whether there are significant residuals.

**Comment by ericagol** [comment]
@educrot 

I made a plot of the transit depths in the two bands from [Ducrot et al. (2020)](https://doi.org/10.1051/0004-6361/201937392), and the depths look very consistent in both bands (see below).

To test for whether the depths are consistent between the two bands,  I took the difference between the depths in the two bands for each planet divided by the sum of the squares of the standard deviations (since the measurement errors in the two bands are independent) and found:

[0.274526, -1.17579, 1.03193, 0.190329, -1.12499, 0.795432, 1.28611]

I then checked for whether these are consistent with normality using the Shapiro-Wilks test (aka W-test) here:

http://www.statskingdom.com/320ShapiroWilk.html

finding a p-value of 0.25 which indicates that the differences between the
depths in the two bands divided by the standard deviations are consistent 
with a normal distribution!    The mean of the distribution is -0.056 and the
standard deviation is 1.045, which both indicate normality as well.


Thus, any differences between the depths in the two bands are consistent 
with statistical random errors, so it is justified to assume that the depth is 
identical in both Spitzer Channels.

![Ch2_vs_Ch1_Ducrot2020](https://user-images.githubusercontent.com/243664/91502291-8a2cc500-e87c-11ea-9f93-980359a86273.png)

**Comment by ericagol** [comment]
@educrot  I've written this reply to the first point above:

`Thanks for pointing this out.  We have already carried out this independent fit to the 
depths of the two Spitzer passbands (Channel 1 at 3.6 micron and Channel 2 at 4.5 micron) 
in Ducrot et al. (2020) (doi:10.1051/0004-6361/201937392).  This fit showed that the depths
in the two passbands for the seven planets are statistically consistent with one another.
Thus, there is no evidence for the depths being different which justifies our assumption
to hold them fixed at the same value.  We gathered more data in Channel 2 for the
outer six planets, so for these the depth value and precision are dominated by the
value at 4.5 micron. Planet b has comparable uncertainties in both Channel 1 and Channel
2, but the depths agree at the 0.27-sigma level.`

**Comment by educrot** [comment]
@ericagol this justification seems great to me. 

Concerning the second comment of the authors, out of curiosity I was wondering if you had a table reporting all the timings outliers at hand in order to check any potential correlation? 

Thanks a lot!

**Comment by ericagol** [comment]
@educrot  Hi Elsa - Yes, here is the list of outliers, which is created with the `outliers.jl` script in the `data/` directory.  -Eric

   1  2   43   7322.51793   7322.51531 -0.00262  0.00071  -3.7  13.6
  95  2  377   7827.14951   7827.14995  0.00044  0.00013   3.3  11.2
 113  2  472   7970.68336   7970.68541  0.00205  0.00041   5.0  25.0
 183  3  164   7653.34604   7653.34548 -0.00056  0.00016  -3.5  12.2
 202  3  208   7759.90502   7759.90281 -0.00221  0.00058  -3.8  14.5
 254  3  334   8065.05003   8065.04723 -0.00280  0.00071  -3.9  15.6
 263  3  480   8418.63096   8418.62948 -0.00149  0.00031  -4.8  23.0
 311  4  193   8038.67754   8038.67921  0.00167  0.00031   5.4  28.9
 319  4  260   8309.99960   8309.98967 -0.00993  0.00249  -4.0  15.9
 320  4  271   8354.54764   8354.55188  0.00424  0.00110   3.9  14.9
 350  5  119   7983.63045   7983.62772 -0.00273  0.00086  -3.2  10.1
 378  6   51   7726.62067   7726.61960 -0.00107  0.00026  -4.1  16.9
 404  7    3   7294.77264   7294.78600  0.01336  0.00390   3.4  11.7
 431  7   93   8406.56914   8406.57038  0.00124  0.00026   4.8  22.6

**Comment by ericagol** [comment]
| Transit number | Planet | Model time | Observed time | Obs - mod | (Obs-mod)/sig | (Obs-mod)^2/sig^2 |
|----|--|----|----------|----------|--------|-------|-----|-----|
|   1|  2|   43|   7322.51793|   7322.51531| -0.00262|  0.00071|  -3.7|  13.6|
|  95|  2|  377|   7827.14951|   7827.14995|  0.00044|  0.00013|   3.3|  11.2|
| 113|  2|  472|   7970.68336|   7970.68541|  0.00205|  0.00041|   5.0|  25.0|
| 183|  3|  164|   7653.34604|   7653.34548| -0.00056|  0.00016|  -3.5|  12.2|
| 202|  3|  208|   7759.90502|   7759.90281| -0.00221|  0.00058|  -3.8|  14.5|
| 254|  3|  334|   8065.05003|   8065.04723| -0.00280|  0.00071|  -3.9|  15.6|
| 263|  3|  480|   8418.63096|   8418.62948| -0.00149|  0.00031|  -4.8|  23.0|
| 311|  4|  193|   8038.67754|   8038.67921|  0.00167|  0.00031|   5.4|  28.9|
| 319|  4|  260|   8309.99960|   8309.98967| -0.00993|  0.00249|  -4.0|  15.9|
| 320|  4|  271|   8354.54764|   8354.55188|  0.00424|  0.00110|   3.9|  14.9|
| 350|  5|  119|   7983.63045|   7983.62772| -0.00273|  0.00086|  -3.2|  10.1|
| 378|  6|   51|   7726.62067|   7726.61960| -0.00107|  0.00026|  -4.1|  16.9|
| 404|  7|    3|   7294.77264|   7294.78600|  0.01336|  0.00390|   3.4|  11.7|
| 431|  7|   93|   8406.56914|   8406.57038|  0.00124|  0.00026|   4.8|  22.6|

**Comment by ericagol** [comment]
| Column 1 Header | Column 2 Header | Column 3 Header |
| --------------- | --------------- | --------------- |
| Row 1 Column 1 | Row 1 Column 2 | Row 1 Column 3 |
| Row 2 Column 1 | Row 2 Column 2 | Row 2 Column 3 |
| Row 3 Column 1 | Row 3 Column 2 | Row 3 Column 3 |

**Comment by ericagol** [comment]
| Transit number | Planet | Model time | Observed time | Obs minus model | Norm resid | Norm resid squared |
|----|---|----|----------|----------|--------|-------|-----|-----|
|   1|  2|   43|   7322.51793|   7322.51531| -0.00262|  0.00071|  -3.7|  13.6|
|  95|  2|  377|   7827.14951|   7827.14995|  0.00044|  0.00013|   3.3|  11.2|
| 113|  2|  472|   7970.68336|   7970.68541|  0.00205|  0.00041|   5.0|  25.0|
| 183|  3|  164|   7653.34604|   7653.34548| -0.00056|  0.00016|  -3.5|  12.2|
| 202|  3|  208|   7759.90502|   7759.90281| -0.00221|  0.00058|  -3.8|  14.5|
| 254|  3|  334|   8065.05003|   8065.04723| -0.00280|  0.00071|  -3.9|  15.6|
| 263|  3|  480|   8418.63096|   8418.62948| -0.00149|  0.00031|  -4.8|  23.0|
| 311|  4|  193|   8038.67754|   8038.67921|  0.00167|  0.00031|   5.4|  28.9|
| 319|  4|  260|   8309.99960|   8309.98967| -0.00993|  0.00249|  -4.0|  15.9|
| 320|  4|  271|   8354.54764|   8354.55188|  0.00424|  0.00110|   3.9|  14.9|
| 350|  5|  119|   7983.63045|   7983.62772| -0.00273|  0.00086|  -3.2|  10.1|
| 378|  6|   51|   7726.62067|   7726.61960| -0.00107|  0.00026|  -4.1|  16.9|
| 404|  7|    3|   7294.77264|   7294.78600|  0.01336|  0.00390|   3.4|  11.7|
| 431|  7|   93|   8406.56914|   8406.57038|  0.00124|  0.00026|   4.8|  22.6|

**Comment by ericagol** [comment]
| Transit number | Planet | Model time | Observed time | Obs - mod | (Obs-mod)/sig | (Obs-mod)^2/sig^2 |
| ---| --- | --- | --- | ---- | --- | --- |
|   1|  2|   43|   7322.51793|   7322.51531| -0.00262|  0.00071|  -3.7|  13.6|
|  95|  2|  377|   7827.14951|   7827.14995|  0.00044|  0.00013|   3.3|  11.2|
| 113|  2|  472|   7970.68336|   7970.68541|  0.00205|  0.00041|   5.0|  25.0|
| 183|  3|  164|   7653.34604|   7653.34548| -0.00056|  0.00016|  -3.5|  12.2|
| 202|  3|  208|   7759.90502|   7759.90281| -0.00221|  0.00058|  -3.8|  14.5|
| 254|  3|  334|   8065.05003|   8065.04723| -0.00280|  0.00071|  -3.9|  15.6|
| 263|  3|  480|   8418.63096|   8418.62948| -0.00149|  0.00031|  -4.8|  23.0|
| 311|  4|  193|   8038.67754|   8038.67921|  0.00167|  0.00031|   5.4|  28.9|
| 319|  4|  260|   8309.99960|   8309.98967| -0.00993|  0.00249|  -4.0|  15.9|
| 320|  4|  271|   8354.54764|   8354.55188|  0.00424|  0.00110|   3.9|  14.9|
| 350|  5|  119|   7983.63045|   7983.62772| -0.00273|  0.00086|  -3.2|  10.1|
| 378|  6|   51|   7726.62067|   7726.61960| -0.00107|  0.00026|  -4.1|  16.9|
| 404|  7|    3|   7294.77264|   7294.78600|  0.01336|  0.00390|   3.4|  11.7|
| 431|  7|   93|   8406.56914|   8406.57038|  0.00124|  0.00026|   4.8|  22.6|

**Comment by ericagol** [comment]
@educrot  

As far as the transit depths, I tried the following:  for each planet, I took the depths from tables A.4 and A.5.  For every planet I computed the difference between each transit depth and the weighted mean of all other transit depths.
I then computed the normalized significance of these differences.

I then applied the Shapiro-Wilk W-test to search for non-Gaussianity.  I found that the standard deviation of the normalized depths is 1.24, indicating that the scatter may be slightly larger than the errors indicate.  Perhaps the errors are slightly underestimated?

However, what's interesting is that the distribution is consistent with a normal distribution:  given the 159 depths measured in your paper, the number of outliers is not excessive.  The probability that the distribution is drawn from N(0,1) is 90%.  Thus, even though the scatter is larger than expected given the uncertainties, there is not significant evidence for non-Gaussian outliers based on the size of the dataset. 

All to say:  I don't think we need to exclude any of the transits from our photodynamic analysis.

That said, the new paper has 188 Spitzer transits:  do you have depths and uncertainties for these additional transits?

**Comment by ericagol** [comment]
Here are the normalized differences:

0.5383343159052377
1.1557648228643174
-0.9240601438143704
0.9707226426283652
-0.8881874973107052
0.4663818186587018
-0.8252741571316853
0.12571930574622625
-0.8334985362631058
0.2155000468518404
0.4397949816434748
1.1631361579720674
-0.5580038090392441
-0.39746921722075146
-0.8406037466411659
-0.4138752150686961
-0.0835598662036803
0.4329926464486453
2.346301927372408
0.7762373838309345
-1.0181220945021774
-0.7084750024447175
1.7916216793193638
1.4877203603878004
-1.0826052917906654
0.39484856597784385
0.34049959377722755
-3.0097011363583372
-0.6564923493826608
-0.04798869959606168
0.32764751424764943
0.10335257945601505
1.0494016207939307
-2.456616118510428
-1.139002863379573
0.4644493165381484
2.383684416504343
0.16579917013554452
-0.772920886390325
-0.6269225251855755
-0.9482672982951162
1.7186562958340237
-0.345237290127266
0.8650108532392923
-0.5695322249189085
-1.5414769423493366
-0.6816796923147217
0.9983787558201979
-0.42000226839114413
0.7388548946989915
-0.24133375208857424
1.5612696556016672
0.8476783915161203
0.7140233126935008
0.3567288501623165
-0.06801254792662406
-0.38850426833145096
-0.6096776809284198
-0.7865694902923879
0.19335668451929383
-0.708829779872006
1.131655491963278
-1.5273743444384869
-2.210683386080371
-0.6922007879562655
-0.9303841728169956
-0.38303883105902903
0.6808284660444842
1.1231131607065445
-0.9541319848197143
1.7373713690422874
0.14170354695333687
1.1959354132849311
0.8820733738688074
-0.5256827857645645
0.10124887156740496
-0.39585520650484113
-0.8435918794000178
1.9741655699741818
1.0651469784184155
-1.0601050827381286
-0.19262269844175559
-0.4170202352428767
-2.072672488316558
-1.485586862006677
0.19873421771339983
1.3799499537272855
-0.017932465544509897
0.1629163079660437
1.444863024772276
1.2400593248965441
-1.3437515109243114
1.1087870417220367
3.276051014741397
-1.6083758218772202
2.462899108412195
0.45756414196446493
-0.22437843231270546
0.31123406103665846
1.2041363108372232
1.5127877892158073
-0.49344682024498016
-2.499681429705762
0.9960940720436489
0.5795107387823185
-1.4699818047518673
0.2846062500270218
1.29026890882315
-1.5924469984999274
-1.5531724151692416
0.020972310385989436
-1.7141301007957666
-0.4945217294025786
1.783922907643299
0.9385690924446131
-1.3592902484660219
-2.4222327760439937
-0.6147281941773716
-1.1766068115345698
1.5721148047103601
0.5982574626571951
1.495910283494649
0.4620053125278422
0.18328946278866326
-0.12728740602200284
1.120685665241847
-1.7343966531786712
1.2412219977874472
-2.0531831173839454
0.7037077758376722
-0.8457701742456091
-0.27787326213774194
0.9401185253470796
0.05936790062633419
-1.647926271801549
-2.439661422169718
-0.14160048830833694
-0.6761036118948399
0.6844552763799044
-0.7851869959610382
2.5432159564991133
0.29941665107786214
1.1747324817042342
-1.8670641413364601
-3.8859565353824963
1.532103747173978
3.509439208103727
1.5023861509446113
-0.6365678774487251
-0.9934967808481507
-1.149463364676164
-0.8717567930184442
-0.8239765439174378
-0.099703211694068
1.9651176373026045
0.752950921106972
-0.5151079207734869
-0.5198906139940672
-1.6568735656482023

**Comment by educrot** [comment]
> As far as the transit depths, I tried the following: for each planet, I took the depths from tables A.4 and A.5. For every planet I computed the difference between each transit depth and the weighted mean of all other transit depths for that planet.
> 
> I then computed the normalized significance of these differences.
> I then applied the Shapiro-Wilk W-test to search for non-Gaussianity in these normalized differences. I found that the standard deviation of the normalized depths is 1.24, indicating that the scatter may be slightly larger than the errors indicate. Perhaps the error bars are slightly underestimated by ~20%?
> However, what's interesting is that the distribution is consistent with a normal distribution: given the 159 depths measured in your paper, the number of outliers is not excessive. The probability that the distribution is drawn from N(0,1) is 90%. Thus, even though the scatter is larger than expected given the uncertainties, there is not significant evidence for non-Gaussian outliers based on the size of the dataset.
> 
> All to say: I don't think we need to exclude any of the transits from our photodynamic analysis.

Ok great, thanks for the calculations.

> 
> That said, the new paper has 188 Spitzer transits: do you have depths and uncertainties for these additional transits?

Ok so just to recap you used the 159 transits depths and errors given in Table A4 and A5 of [our paper](https://www.aanda.org/articles/aa/pdf/2020/08/aa37392-19.pdf), such that the 29 missing transits (to go to 188) are the blended/partial ones. 

We did not included those transits in the global analyses but carried out individual analyses for each of them, the depths and errors obtained can be founded in Table A3, where the channel is also specified.

**Comment by ericagol** [comment]
@educrot  When I include those additional 29 transit depths, planet b has two significant outliers (assuming I corrected typos on depth uncertainties correctly).  

- [  ]  I should check the photo dynamical model for these two transits to see whether there are significant residuals.

**Comment by ericagol** [comment]
@educrot   I examined these two outliers, and with the photo dynamical model I find that the depths of these two transits are consistent with the depth of the fit to all transits at the better than 1-sigma level.   So, I don't think we have any significant outliers!

I will write the response to the referee and resolve this.
