### ISSUE TITLE
Love number of planets

### ISSUE THREAD

**Issue by ericagol** [ericagol/TRAPPIST1_Spitzer#7]
- [ ] The compositional models proposed in the paper - water-rich, coreless, or iron-poor - the Love number of the planets may vary.  Could Caroline compute these for the different interior models?  Could Emeline estimate how sensitive the tidal models are to `k_2`?  How much does this influence the shapes of the planets?  This paper discusses the value of measuring `k_2` in constraining the interior compositions:

[Kellerman et al. (2018)](https://doi.org/10.1051/0004-6361/201731775)

**Comment by CarolineDorn** [comment]
Indeed, I could compute them, it will take me some time to implement. I think it would be good to check with Emeline which k_2 approximation she is using.

**Comment by ericagol** [comment]
@CarolineDorn  Let's skip k<sub>2</sub> for now.
